name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: check out repository
        uses: actions/checkout@v2
        
      - name: test
        run: touch filetest
        
      - name: deploys the project
        run: ansible-playbook site.yaml

  test:
    runs-on: [self-hosted, Linux, X64]
    needs: [build]
    steps:     
      - name: curl the loadbalancer for database output
        run: curl http://ucpe.swisscom.com/api.php >> results
